# Generated by Django 5.1.5 on 2025-02-24 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='buycars.make', verbose_name='Марка')),
            ],
            options={
                'unique_together': {('name', 'make')},
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(blank=True, max_length=20, verbose_name='Тип кузова')),
                ('engine_volume', models.FloatField(blank=True, verbose_name='Объем двигателя')),
                ('description', models.TextField(blank=True, default='Напишите продавцу и узнайте подробности!', null=True, verbose_name='Описание автомобиля')),
                ('year_of_release', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования объявления')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('condition', models.CharField(choices=[('n', 'Новый'), ('s', 'Б/У'), ('p', 'На запчасти')], default='s', max_length=1, verbose_name='Состояние')),
                ('transmission_box', models.CharField(choices=[('m', 'Механика'), ('a', 'Автомат'), ('r', 'Робот')], default='m', max_length=1, verbose_name='Коробка передач')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет авто')),
                ('fuel_type', models.CharField(choices=[('b', 'Бензин'), ('d', 'Дизель'), ('g', 'Газ'), ('e', 'Электричка')], max_length=1, verbose_name='Тип топлива')),
                ('Mileage', models.IntegerField(blank=True, verbose_name='Пробег')),
                ('make', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.make', verbose_name='Марка автомобиля')),
                ('model', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.model', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_volume', models.FloatField(blank=True, verbose_name='Объем двигателя в см^3')),
                ('description', models.TextField(blank=True, default='Напишите продавцу и узнайте подробности!', null=True, verbose_name='Описание транспорта')),
                ('year_of_release', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования объявления')),
                ('price', models.FloatField(blank=True, verbose_name='Цена')),
                ('condition', models.CharField(choices=[('n', 'Новый'), ('s', 'Б/У'), ('p', 'На запчасти')], default='s', max_length=1, verbose_name='Состояние')),
                ('main_gear', models.CharField(blank=True, choices=[('c', 'Цепь'), ('k', 'Кардан'), ('r', 'Ремень')], max_length=1, verbose_name='Главная передача')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Цвет транспорта')),
                ('make', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.make', verbose_name='Марка автомобиля')),
                ('model', models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.model', verbose_name='Модель авто')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False, verbose_name='Продавец?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
