# Generated by Django 5.1.5 on 2025-02-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=20)),
                ('engine_volume', models.FloatField()),
                ('description', models.TextField(default='Напишите продавцу и узнайте подробности!', null=True)),
                ('year_of_release', models.IntegerField()),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
