# Generated by Django 5.1.5 on 2025-02-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='Mileage',
            field=models.IntegerField(blank=True, default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(blank=True, choices=[('1', 'Седан'), ('2', 'Универсал'), ('3', 'Хетчбек'), ('4', 'Купе'), ('5', 'Лимузин'), ('6', 'Микроавтобус'), ('7', 'Минивэн'), ('8', 'Хардтоп'), ('9', 'Таун-кар'), ('a', 'Комби'), ('b', 'Лифтбек'), ('c', 'Фастбек'), ('d', 'Кабриолет'), ('e', 'Пикап'), ('f', 'Фургон')], max_length=1, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации объявления'),
        ),
    ]
