# Generated by Django 5.1.5 on 2025-04-12 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0002_alter_cars_condition_alter_cars_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='color',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ-]*$', 'Разрешена только кириллица и дефис')], verbose_name='Цвет авто'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.CharField(blank=True, max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ\\s-]*$', 'Разрешены только буквы, пробел и дефис')], verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='color',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^[а-яА-ЯёЁ-]*$', 'Разрешена только кириллица и дефис')], verbose_name='Цвет транспорта'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='make',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-ЯёЁ\\s-]*$', 'Разрешены только буквы, пробел и дефис')], verbose_name='Марка мотоцикла'),
        ),
    ]
