# Generated by Django 5.1.5 on 2025-02-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0002_cars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moto_brand', models.CharField(blank=True, max_length=30, verbose_name='Марка автомобиля')),
                ('moto_model', models.CharField(blank=True, max_length=30, verbose_name='Модель автомобиля')),
                ('engine_volume', models.FloatField(blank=True, verbose_name='Объем двигателя')),
                ('description', models.TextField(blank=True, default='Напишите продавцу и узнайте подробности!', null=True, verbose_name='Описание транспорта')),
                ('year_of_release', models.IntegerField(blank=True, verbose_name='Год выпуска')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования объявления')),
                ('price', models.TextField(blank=True, default='Договорная', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Мотоцикл',
                'verbose_name_plural': 'Мотоциклы',
                'ordering': ['-published'],
            },
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['-published'], 'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_brand',
            field=models.CharField(blank=True, max_length=30, verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_model',
            field=models.CharField(blank=True, max_length=30, verbose_name='Модель автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='car_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=models.TextField(blank=True, default='Напишите продавцу и узнайте подробности!', null=True, verbose_name='Описание автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='engine_volume',
            field=models.FloatField(blank=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.TextField(blank=True, default='Договорная', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='published',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата опубликования объявления'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='year_of_release',
            field=models.IntegerField(blank=True, verbose_name='Год выпуска'),
        ),
    ]
