# Generated by Django 5.1.5 on 2025-02-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0003_moto_alter_cars_options_alter_cars_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='condition',
            field=models.CharField(choices=[('n', 'Новый'), ('s', 'Б/У'), ('p', 'На запчасти')], default='s', max_length=1, verbose_name='Состояние'),
        ),
        migrations.AddField(
            model_name='cars',
            name='transmission_box',
            field=models.CharField(choices=[('m', 'Механика'), ('a', 'Автомат'), ('r', 'Робот')], default='m', max_length=1, verbose_name='Коробка передач'),
        ),
        migrations.AddField(
            model_name='moto',
            name='condition',
            field=models.CharField(choices=[('n', 'Новый'), ('s', 'Б/У'), ('p', 'На запчасти')], default='s', max_length=1, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='engine_volume',
            field=models.FloatField(blank=True, verbose_name='Объем двигателя в см^3'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='moto_brand',
            field=models.CharField(blank=True, max_length=30, verbose_name='Марка мотоцикла'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='moto_model',
            field=models.CharField(blank=True, max_length=30, verbose_name='Модель мотоцикла'),
        ),
    ]
