# Generated by Django 5.1.5 on 2025-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0005_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='price',
            field=models.FloatField(blank=True, verbose_name='Цена'),
        ),
    ]
