# Generated by Django 5.1.5 on 2025-03-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Продавец?'),
        ),
    ]
