# Generated by Django 5.1.5 on 2025-04-01 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buycars.moto', verbose_name='Мотоцикл')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные',
                'unique_together': {('user', 'moto')},
            },
        ),
    ]
