# Generated by Django 5.1.5 on 2025-04-12 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0009_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Список избранных автомобилей', 'verbose_name_plural': 'Избранные авто'},
        ),
        migrations.AlterModelOptions(
            name='favorite_moto',
            options={'verbose_name': 'Список избранных мотоциклов', 'verbose_name_plural': 'Избранные мотоциклы'},
        ),
        migrations.AlterField(
            model_name='moto',
            name='make',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.make', verbose_name='Марка мотоцикла'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='model',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.model', verbose_name='Модель'),
        ),
    ]
