# Generated by Django 5.1.5 on 2025-04-12 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0009_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.PROTECT, to='buycars.make', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.PROTECT, to='buycars.model', verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buycars.cars', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='favorite_moto',
            name='moto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buycars.moto', verbose_name='Мотоцикл'),
        ),
        migrations.AlterField(
            model_name='favorite_moto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='buycars.make', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='make',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.PROTECT, to='buycars.make', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='moto',
            name='model',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.PROTECT, to='buycars.model', verbose_name='Модель авто'),
        ),
    ]
