# Generated by Django 5.1.5 on 2025-04-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0010_alter_favorite_options_alter_favorite_moto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Номер телефона'),
        ),
    ]
