# Generated by Django 5.1.5 on 2025-04-12 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0010_alter_cars_make_alter_cars_model_alter_favorite_car_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite_moto',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='favorite_moto',
            name='moto',
        ),
        migrations.RemoveField(
            model_name='favorite_moto',
            name='user',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='Favorite_moto',
        ),
    ]
