# Generated by Django 5.1.5 on 2025-04-12 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0011_alter_profile_phone'),
        ('buycars', '0012_favorite_favorite_moto'),
    ]

    operations = [
    ]
