# Generated by Django 5.1.5 on 2025-04-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buycars', '0013_merge_20250412_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='make',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.make', verbose_name='Марка автомобиля'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='model',
            field=models.ForeignKey(blank=True, max_length=30, on_delete=django.db.models.deletion.CASCADE, to='buycars.model', verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='model',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='buycars.make', verbose_name='Марка'),
        ),
    ]
